# 基础配置文件

spring:
  application:
    name: scaffold
  profiles:
    active: dev     # 配置文件环境
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true     # 接口404时抛出异常
  resources:
    add-mappings: false

server:
  servlet:
    context-path: /v1     # 应用路径，可以通过设置路径来控制版本
  tomcat:
    uri-encoding: UTF-8

jasypt:
  encryptor:
    # 加密
    password: 2190268123asd
    # 指定加密方式
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
