# 开发环境配置文件
server:
  port: 8219     # Springboot占用端口

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver     # 数据库驱动
      url: jdbc:mysql://您的数据库地址:您的数据库端口/seed?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false     # 数据库链接
      username: ENC(xXYHEoPD8rTpHa+PVM7/vA==)     # 数据库账号（需要替换成您的数据库账号）
      password: ENC(IoNLw/J8J5q2BfDo3PDjxpugNDqGFWuM)     # 数据库密码（需要替换成您的数据库密码）
      type: com.alibaba.druid.pool.DruidDataSource
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
  redis:
    password:
    port: 6379
    #线上环境
    host: localhost
    lettuce:
      pool:
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 0
        # 最大活跃链接数 默认8
        max-active: 8
    #请求时间
    timeout: 5000
  devtools:
    restart:
      enabled: true     # 开启热更新

# 日志配置
logging:
  level:
    com.jxys: debug
    org.springframework: warn
